# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\tmp\github\40623242-final\ui\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(518, 457)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.clearMemoryButton = QtWidgets.QPushButton(Dialog)
        self.clearMemoryButton.setMinimumSize(QtCore.QSize(82, 52))
        self.clearMemoryButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.clearMemoryButton.setFont(font)
        self.clearMemoryButton.setObjectName("clearMemoryButton")
        self.gridLayout.addWidget(self.clearMemoryButton, 1, 0, 1, 1)
        self.divisionButton = QtWidgets.QPushButton(Dialog)
        self.divisionButton.setMinimumSize(QtCore.QSize(82, 52))
        self.divisionButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.divisionButton.setFont(font)
        self.divisionButton.setObjectName("divisionButton")
        self.gridLayout.addWidget(self.divisionButton, 2, 3, 1, 1)
        self.one = QtWidgets.QPushButton(Dialog)
        self.one.setMinimumSize(QtCore.QSize(82, 52))
        self.one.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 4, 0, 1, 1)
        self.six = QtWidgets.QPushButton(Dialog)
        self.six.setMinimumSize(QtCore.QSize(82, 52))
        self.six.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 3, 2, 1, 1)
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setMinimumSize(QtCore.QSize(82, 52))
        self.clearButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 4, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setMinimumSize(QtCore.QSize(466, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(466, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 5)
        self.five = QtWidgets.QPushButton(Dialog)
        self.five.setMinimumSize(QtCore.QSize(82, 52))
        self.five.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 3, 1, 1, 1)
        self.seven = QtWidgets.QPushButton(Dialog)
        self.seven.setMinimumSize(QtCore.QSize(82, 52))
        self.seven.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 2, 0, 1, 1)
        self.plusButton = QtWidgets.QPushButton(Dialog)
        self.plusButton.setMinimumSize(QtCore.QSize(82, 52))
        self.plusButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.gridLayout.addWidget(self.plusButton, 5, 3, 1, 1)
        self.nine = QtWidgets.QPushButton(Dialog)
        self.nine.setMinimumSize(QtCore.QSize(82, 52))
        self.nine.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 2, 2, 1, 1)
        self.three = QtWidgets.QPushButton(Dialog)
        self.three.setMinimumSize(QtCore.QSize(82, 52))
        self.three.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 4, 2, 1, 1)
        self.point = QtWidgets.QPushButton(Dialog)
        self.point.setMinimumSize(QtCore.QSize(82, 52))
        self.point.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.point.setFont(font)
        self.point.setObjectName("point")
        self.gridLayout.addWidget(self.point, 5, 1, 1, 1)
        self.zero = QtWidgets.QPushButton(Dialog)
        self.zero.setMinimumSize(QtCore.QSize(82, 52))
        self.zero.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 5, 0, 1, 1)
        self.two = QtWidgets.QPushButton(Dialog)
        self.two.setMinimumSize(QtCore.QSize(82, 52))
        self.two.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 4, 1, 1, 1)
        self.equalButton = QtWidgets.QPushButton(Dialog)
        self.equalButton.setMinimumSize(QtCore.QSize(82, 52))
        self.equalButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.gridLayout.addWidget(self.equalButton, 5, 2, 1, 1)
        self.eight = QtWidgets.QPushButton(Dialog)
        self.eight.setMinimumSize(QtCore.QSize(82, 52))
        self.eight.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 2, 1, 1, 1)
        self.four = QtWidgets.QPushButton(Dialog)
        self.four.setMinimumSize(QtCore.QSize(82, 52))
        self.four.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 3, 0, 1, 1)
        self.minusButton = QtWidgets.QPushButton(Dialog)
        self.minusButton.setMinimumSize(QtCore.QSize(82, 52))
        self.minusButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.gridLayout.addWidget(self.minusButton, 4, 3, 1, 1)
        self.plusminus = QtWidgets.QPushButton(Dialog)
        self.plusminus.setMinimumSize(QtCore.QSize(82, 52))
        self.plusminus.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.plusminus.setFont(font)
        self.plusminus.setObjectName("plusminus")
        self.gridLayout.addWidget(self.plusminus, 5, 4, 1, 1)
        self.timesButton = QtWidgets.QPushButton(Dialog)
        self.timesButton.setMinimumSize(QtCore.QSize(82, 52))
        self.timesButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.timesButton.setFont(font)
        self.timesButton.setObjectName("timesButton")
        self.gridLayout.addWidget(self.timesButton, 3, 3, 1, 1)
        self.powerButton = QtWidgets.QPushButton(Dialog)
        self.powerButton.setMinimumSize(QtCore.QSize(82, 52))
        self.powerButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.powerButton.setFont(font)
        self.powerButton.setObjectName("powerButton")
        self.gridLayout.addWidget(self.powerButton, 2, 4, 1, 1)
        self.clearAllButton = QtWidgets.QPushButton(Dialog)
        self.clearAllButton.setMinimumSize(QtCore.QSize(82, 52))
        self.clearAllButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.clearAllButton.setFont(font)
        self.clearAllButton.setObjectName("clearAllButton")
        self.gridLayout.addWidget(self.clearAllButton, 3, 4, 1, 1)
        self.setMemoryButton = QtWidgets.QPushButton(Dialog)
        self.setMemoryButton.setMinimumSize(QtCore.QSize(82, 52))
        self.setMemoryButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.setMemoryButton.setFont(font)
        self.setMemoryButton.setObjectName("setMemoryButton")
        self.gridLayout.addWidget(self.setMemoryButton, 1, 1, 1, 1)
        self.addToMemoryButton = QtWidgets.QPushButton(Dialog)
        self.addToMemoryButton.setMinimumSize(QtCore.QSize(82, 52))
        self.addToMemoryButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.addToMemoryButton.setFont(font)
        self.addToMemoryButton.setObjectName("addToMemoryButton")
        self.gridLayout.addWidget(self.addToMemoryButton, 1, 2, 1, 1)
        self.lessToMemoryButton = QtWidgets.QPushButton(Dialog)
        self.lessToMemoryButton.setMinimumSize(QtCore.QSize(82, 52))
        self.lessToMemoryButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.lessToMemoryButton.setFont(font)
        self.lessToMemoryButton.setObjectName("lessToMemoryButton")
        self.gridLayout.addWidget(self.lessToMemoryButton, 1, 3, 1, 1)
        self.readMemoryButton = QtWidgets.QPushButton(Dialog)
        self.readMemoryButton.setMinimumSize(QtCore.QSize(82, 52))
        self.readMemoryButton.setMaximumSize(QtCore.QSize(82, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.readMemoryButton.setFont(font)
        self.readMemoryButton.setObjectName("readMemoryButton")
        self.gridLayout.addWidget(self.readMemoryButton, 1, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.clearMemoryButton.setText(_translate("Dialog", "MC"))
        self.divisionButton.setText(_translate("Dialog", "/"))
        self.one.setText(_translate("Dialog", "1"))
        self.six.setText(_translate("Dialog", "6"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
        self.five.setText(_translate("Dialog", "5"))
        self.seven.setText(_translate("Dialog", "7"))
        self.plusButton.setText(_translate("Dialog", "+"))
        self.nine.setText(_translate("Dialog", "9"))
        self.three.setText(_translate("Dialog", "3"))
        self.point.setText(_translate("Dialog", "."))
        self.zero.setText(_translate("Dialog", "0"))
        self.two.setText(_translate("Dialog", "2"))
        self.equalButton.setText(_translate("Dialog", "="))
        self.eight.setText(_translate("Dialog", "8"))
        self.four.setText(_translate("Dialog", "4"))
        self.minusButton.setText(_translate("Dialog", "-"))
        self.plusminus.setText(_translate("Dialog", "-/+"))
        self.timesButton.setText(_translate("Dialog", "X"))
        self.powerButton.setText(_translate("Dialog", "sqrt"))
        self.clearAllButton.setText(_translate("Dialog", "Clearall"))
        self.setMemoryButton.setText(_translate("Dialog", "MS"))
        self.addToMemoryButton.setText(_translate("Dialog", "M+"))
        self.lessToMemoryButton.setText(_translate("Dialog", "M-"))
        self.readMemoryButton.setText(_translate("Dialog", "MR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

